apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qckugnaj0-python
  janus-idp.io/tekton: qckugnaj0-python
  backstage.io/kubernetes-id: qckugnaj0-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qckugnaj0-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
